name: flutter_arb_organizer
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.3
  bitsdojo_window: ^0.1.1+1
  file_picker: ^8.3.1
  desktop_drop: ^0.5.0
  archive: ^4.0.2
  flutter_improved_scrolling: ^0.0.3
  cross_file: ^0.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
